<?php

return [
    'codex' => [
        'bin' => 'codex',
        'cwd' => '/home/web',
        'debug_dir' => __DIR__ . '/../var/codex-debug',
        'initial_session_id' => '',
        'extra_args' => [
            '-s',
            'read-only',
            '--skip-git-repo-check',
            '--json',
        ],
        'session_label_prefix' => 'runtime-chat-',
        'bootstrap_prompt' => '',
    ],
    'background' => [
        'enabled' => true,
        'bot_pid_file' => __DIR__ . '/../var/run/bot.pid',
        'bot_lock_file' => __DIR__ . '/../var/run/bot.lock',
        'max_transport_pid_file' => __DIR__ . '/../var/run/max-transport.pid',
        'max_transport_lock_file' => __DIR__ . '/../var/run/max-transport.lock',
        'max_outbound_consumer_pid_file' => __DIR__ . '/../var/run/max-outbound-consumer.pid',
        'max_outbound_consumer_lock_file' => __DIR__ . '/../var/run/max-outbound-consumer.lock',
        'exec_watcher_pid_file' => __DIR__ . '/../var/run/exec-watcher.pid',
        'exec_watcher_shutdown_flag_file' => __DIR__ . '/../var/run/exec-watcher.shutdown.flag',
        'command_watcher_pid_file' => __DIR__ . '/../var/run/command-watcher.pid',
        'command_watcher_shutdown_flag_file' => __DIR__ . '/../var/run/command-watcher.shutdown.flag',
        'control_watcher_pid_file' => __DIR__ . '/../var/run/control-watcher.pid',
        'control_watcher_shutdown_flag_file' => __DIR__ . '/../var/run/control-watcher.shutdown.flag',
        'manager_worker_pid_file' => __DIR__ . '/../var/run/max-manager-worker.pid',
        'manager_worker_shutdown_flag_file' => __DIR__ . '/../var/run/manager-worker.shutdown.flag',
        'orchestrator_pid_file' => __DIR__ . '/../var/run/max-orchestrator.pid',
        'scheduler_worker_pid_file' => __DIR__ . '/../var/run/scheduler-worker.pid',
        'scheduler_worker_shutdown_flag_file' => __DIR__ . '/../var/run/scheduler-worker.shutdown.flag',
        'idle_watchdog_pid_file' => __DIR__ . '/../var/run/idle-watchdog.pid',
        'idle_watchdog_shutdown_flag_file' => __DIR__ . '/../var/run/idle-watchdog.shutdown.flag',
    ],
    'transport' => [
        'allowed_channel_ids' => [],
        'outbound_poll_interval_ms' => 500,
        'progress_keepalive_ms' => 4000,
        'message_chunk_size' => 3800,
    ],
    'router' => [
        'base_url' => 'https://cdx-router.example',
        'core_token' => '',
        'transport_token' => '',
        'core_events_wait_seconds' => 0,
        'core_events_limit' => 1,
    ],
    'max' => [
        'instance_id' => 'max_main',
        'api_token' => '',
        'bot_username' => '',
        'long_poll_timeout_seconds' => 30,
        'long_poll_limit' => 100,
        'long_poll_retry_delay_ms' => 5000,
        'long_poll_state_file' => __DIR__ . '/../var/state/max-long-poll-state.json',
        'webhook_secret' => '',
        'webhook_header' => 'X-Max-Bot-Api-Secret',
        'status_channel_ids' => [],
        'admin_channel_id' => null,
        'transport_shutdown_flag_file' => __DIR__ . '/../var/run/max-transport.shutdown.flag',
        'outbound_consumer_shutdown_flag_file' => __DIR__ . '/../var/run/max-outbound-consumer.shutdown.flag',
        'transport_state_file' => __DIR__ . '/../var/state/max-transport-state.json',
    ],
    'telegram' => [
        'instance_id' => 'telegram_main',
        'bot_token' => '',
        'base_url' => 'https://api.telegram.org',
        'endpoint_prefix' => 'bot',
        'allowed_chat_ids' => [],
        'poll_timeout' => 25,
        'poll_limit' => 100,
        'poll_retry_delay_ms' => 5000,
        'long_poll_state_file' => __DIR__ . '/../var/state/telegram-long-poll-state.json',
    ],
    'exec_watcher' => [
        'poll_interval_ms' => 1000,
        'default_cwd' => '/home/web',
        'default_timeout' => 600,
        'allowed_workdirs' => ['/home/web'],
        'deny_patterns' => [
            '/(^|[[:space:];|&])sudo([[:space:]]|$)/',
        ],
        'queue_new' => __DIR__ . '/../var/exec-queue/new',
        'queue_running' => __DIR__ . '/../var/exec-queue/running',
        'queue_done' => __DIR__ . '/../var/exec-queue/done',
        'queue_failed' => __DIR__ . '/../var/exec-queue/failed',
        'results_dir' => __DIR__ . '/../var/exec-results',
        'lock_file' => __DIR__ . '/../var/run/exec-watcher.lock',
    ],
    'command_watcher' => [
        'poll_interval_ms' => 1000,
        'default_cwd' => '/home/web',
        'default_timeout' => 600,
        'allowed_workdirs' => ['/home/web'],
        'deny_patterns' => [
            '/(^|[[:space:];|&])sudo([[:space:]]|$)/',
        ],
        'queue_new' => __DIR__ . '/../var/command-queue/new',
        'queue_running' => __DIR__ . '/../var/command-queue/running',
        'queue_done' => __DIR__ . '/../var/command-queue/done',
        'queue_failed' => __DIR__ . '/../var/command-queue/failed',
        'results_dir' => __DIR__ . '/../var/command-results',
        'lock_file' => __DIR__ . '/../var/run/command-watcher.lock',
    ],
    'control_queue' => [
        'poll_interval_ms' => 1000,
        'queue_new' => __DIR__ . '/../var/control-queue/new',
        'queue_running' => __DIR__ . '/../var/control-queue/running',
        'queue_done' => __DIR__ . '/../var/control-queue/done',
        'queue_failed' => __DIR__ . '/../var/control-queue/failed',
        'results_dir' => __DIR__ . '/../var/control-results',
        'lock_file' => __DIR__ . '/../var/run/control-watcher.lock',
    ],
    'manager_queue' => [
        'poll_interval_ms' => 1000,
        'idle_status_text' => 'Свободен',
        'busy_status_template' => 'Начал выполнение задачи %s',
        'restart_status_text' => 'Restarting...',
        'ready_message_text' => 'Ready.',
        'queue_new' => __DIR__ . '/../var/manager-queue/new',
        'queue_running' => __DIR__ . '/../var/manager-queue/running',
        'queue_done' => __DIR__ . '/../var/manager-queue/done',
        'queue_failed' => __DIR__ . '/../var/manager-queue/failed',
        'results_dir' => __DIR__ . '/../var/manager-results',
        'lock_file' => __DIR__ . '/../var/run/manager-worker.lock',
    ],
    'scheduled_queue' => [
        'poll_interval_ms' => 10000,
        'queue_dir' => __DIR__ . '/../var/scheduled-queue',
        'lock_file' => __DIR__ . '/../var/run/scheduler-worker.lock',
    ],
    'outbound_queue' => [
        'queue_new' => __DIR__ . '/../var/outbound-queue/new',
        'queue_done' => __DIR__ . '/../var/outbound-queue/done',
        'queue_failed' => __DIR__ . '/../var/outbound-queue/failed',
    ],
    'orchestrator' => [
        'poll_interval_ms' => 10000,
        'state_file' => __DIR__ . '/../var/state/orchestrator-state.json',
        'shutdown_flag_file' => __DIR__ . '/../var/run/orchestrator.shutdown.flag',
        'admin_channel_id' => null,
        'default_manager_priority' => 40,
        'default_manager_prompt' => 'A background job finished. Assess the result, decide whether a follow-up step is needed, and if needed enqueue it.',
        'transport_prefix' => '🧩'
    ],
    'idle_watchdog' => [
        'enabled' => false,
        'poll_interval_seconds' => 60,
        'chat_idle_seconds' => 300,
        'cooldown_seconds' => 300,
        'projects_scan_root' => '/home/web/Документы',
        'prompt' => 'Take the next concrete step for the selected project.',
        'active_hours_start' => 0,
        'active_hours_end' => 0,
        'running_stall_nudge_after_seconds' => 300,
        'enqueue_priority' => 20,
        'state_file' => __DIR__ . '/../var/state/idle-watchdog-state.json',
        'lock_file' => __DIR__ . '/../var/run/idle-watchdog.lock',
        'transport_prefix' => '⚙️'
    ],
    'chat_routing' => [
        'deny_message' => 'This transport is not configured for this channel.',
        'routes' => [
            'cli-test' => [
                'session_id' => 'replace-with-session-id',
            ],
        ],
    ],
    'storage' => [
        'root' => __DIR__ . '/../var',
        'state_file' => __DIR__ . '/../var/state/state.json',
        'manager_state_file' => __DIR__ . '/../var/state/manager-state.json',
        'log_file' => __DIR__ . '/../var/log/runtime.log',
        'tmp_dir' => __DIR__ . '/../var/tmp',
    ],
];
